# Reading List {-}

ASCP makes it clear that their suggested reading/reference list for the Technologist in Chemistry, C(ASCP), and the Specialist in Chemistry, SH(ASCP), certification exams "is intended only as a partial reference source". The suggested reading/reference list below was last revised on ASCP's website January 2025

## **Journals** {-}
*   <a href="https://clsjournal.ascls.org/" target="_blank">Clinical Laboratory Science</a>. Published by American Society for Clinical Laboratory Science
*   <a href="https://academic.oup.com/clinchem" target="_blank">Clinical Chemistry</a>. Published by Oxford Universtiy Press
*   <a href="https://academic.oup.com/labmed" target="_blank">Laboratory Medicine</a>. Published by Oxford University Press
*   <a href="https://www.mlo-online.com/" target="_blank">Medical Laboratory Observer</a>. Published by Endeavor Business Media, LLC

## **Texts** {-}
*   Clarke, W. & Marzinke, M. (Eds.). (2020). <a href="https://www.amazon.com/Contemporary-Practice-Clinical-Chemistry-William-dp-0128154993/dp/0128154993" target="_blank">Contemporary Practice in Clinical Chemistry</a> (4th ed.). Washington D.C.: AACC
Press
*   Bishop, M.L., et al. (2022). <a href="https://www.amazon.com/Clinical-Chemistry-Principles-Techniques-Correlations/dp/1284238865" target="_blank">Clinical Chemistry: Principles, Techniques, and Correlations</a> (9th ed.). Jones & Bartlett Learning
*   Rifai, N., et al. (2023). <a href="https://www.amazon.com/Fundamentals-Clinical-Chemistry-Molecular-Diagnostics-dp-0323935834/dp/0323935834/ref=dp_ob_title_bk" target="_blank">Tietz Fundamentals of Clinical Chemistry and Molecular Diagnostics</a> (9th ed.). St. Louis, Missouri: Elsevier
*   Rifai, N., et al. (2022). <a href="https://www.amazon.com/Textbook-Laboratory-Chemistry-Molecular-Diagnostics/dp/0323775721" target="_blank">Tietz Textbook of Laboratory Medicine</a> (7th ed.). Elsevier Health Sciences. This reference is more appropriate for the Specialist (SC) level

## **Laboratory Safety** {-}
*   Davis, D.L. (2016). <a href="https://store.ascp.org/productlisting/productdetail?productId=58808536" target="_blank">Laboratory Safety: A Self-Assessment Workbook</a> (2nd ed.). Chicago: ASCP Press

## **Laboratory Management** {-}

These texts are more appropriate for the SC Level

*   Garcia, L.S., et al. (Eds.). (2024). <a href="https://www.amazon.com/Clinical-Laboratory-Management-ASM-Books-dp-1683673913/dp/1683673913" target="_blank">Clinical Laboratory Management</a> (3rd ed.). Washington D.C.: ASM Press
*   Harmening, D.M. (2020). <a href="https://www.amazon.com/Laboratory-Management-Principles-Processes-Fourth/dp/0943903181" target="_blank">Laboratory Management, Principles and Processes</a> (4th ed.). St. Petersburg, FL: D. H. Publishing & Consulting Inc
*   McPherson, R.A. & Pincus, M.R. (2021). <a href="https://www.amazon.com/Clinical-Diagnosis-Management-Laboratory-Methods-dp-0323673201/dp/0323673201" target="_blank">Henry’s Clinical Diagnosis and Management by Laboratory Methods</a> (24th ed.). Philadelphia: Elsevier

## **Online** {-}
*   <a href="https://myadlm.org/" target="_blank">Association for Diagnostics & Laboratory Medicine (ADLM) (formerly AACC)</a>
*   <a href="https://clsi.org/" target="_blank">Clinical and Laboratory Standards Institute (CLSI)</a>
*   <a href="https://www.cap.org/" target="_blank">College of American Pathologists (CAP)</a>
*   <a href="https://medtraining.org/" target="_blank">Medical Training Solutions (MTS)</a>
*   <a href="https://www.jointcommission.org/" target="_blank">The Joint Commission (TJC)</a>
*   <a href="https://westgard.com/" target="_blank">Westgard QC</a>